<link rel="apple-touch-icon" sizes="180x180" href="/objects/images/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/objects/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/objects/images/icons/favicon-16x16.png">
<link rel="manifest" href="/objects/images/icons/site.webmanifest">
<link rel="mask-icon" href="/objects/images/icons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="theme-color" content="#ffffff">
theme: jekyll-theme-slate
