version: '2.4'
services:
  timesketch:
    image: aorlikoski/skadi_timesketch:1.4
    container_name: timesketch
    ports:
      - 127.0.0.1:5000:5000
    links:
      - elasticsearch
      - postgres
      - redis
      - neo4j
    environment:
      - TIMESKETCH_USER=${TIMESKETCH_USER}
      - TIMESKETCH_PASSWORD=${TIMESKETCH_PASSWORD}
    cpus: 1
    mem_reservation: 1gb
    volumes:
      - /etc/timesketch.conf:/etc/timesketch.conf
      - tssockets:/var/timesketch/
    networks:
      - esnet
    restart: always

  postgres:
    image: postgres:11
    container_name: postgres
    cpus: .1
    mem_reservation: 100m
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - esnet
    restart: always

  redis:
    image: redis:5
    container_name: redis
    cpus: .1
    mem_reservation: 100m
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redisdata:/var/lib/redis
    networks:
      - esnet
    restart: always

  neo4j:
    image: neo4j:3.5
    container_name: neo4j
    cpus: .1
    mem_reservation: 100m
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4jdata:/var/lib/neo4j/data
    networks:
      - esnet
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    ports:
      - 127.0.0.1:9200:9200
    cpus: 2
    mem_reservation: 1500m
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${HEAP_SIZE} -Xmx${HEAP_SIZE}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    ports:
      - 127.0.0.1:5601:5601
    cpus: 1
    mem_reservation: 1gb
    environment:
      SERVER_BASEPATH: /kibana
    networks:
      - esnet
    restart: always

  cerebro:
    image: lmenezes/cerebro:0.8.1
    container_name: cerebro
    ports:
      - 127.0.0.1:9000:9000
    cpus: 1
    mem_reservation: 500m
    links:
      - elasticsearch
    networks:
      - esnet
    restart: always

  cyberchef:
    image: aorlikoski/skadi_cyberchef:latest
    container_name: cyberchef
    ports:
      - 127.0.0.1:8000:8000
    cpus: .1
    mem_reservation: 100m
    networks:
      - ccnet
    restart: always

  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
      - /etc/nginx/.skadi_auth:/etc/nginx/.skadi_auth
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /opt/CyLR:/usr/share/nginx/html/downloads
      - tssockets:/var/timesketch/
    network_mode: "host"
    ports:
      - 80:80
      - 443:443
    cpus: .5
    mem_reservation: 100m
    restart: always

  portainer:
    image: portainer/portainer:1.20.2
    container_name: portainer
    volumes:
      - portainerdata:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --no-auth
    pid: host
    networks:
      - ccnet
    ports:
      - 127.0.0.1:7000:9000
    cpus: .2
    mem_reservation: 200m
    restart: always

volumes:
  esdata1:
    driver: local
  neo4jdata:
    driver: local
  pgdata:
    driver: local
  redisdata:
    driver: local
  tssockets:
    driver: local
  portainerdata:
    driver: local

networks:
  esnet:
  ccnet:
